In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
## Defining vocabulary size
voc_size=10000

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4995, 8565, 5021, 613],
 [4995, 8565, 5021, 9121],
 [4995, 4511, 5021, 146],
 [2837, 7638, 2687, 1832, 6147],
 [2837, 7638, 2687, 1832, 384],
 [819, 4995, 2813, 5021, 3012],
 [9526, 2121, 6212, 1832]]

In [10]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4995 8565 5021  613]
 [   0    0    0    0 4995 8565 5021 9121]
 [   0    0    0    0 4995 4511 5021  146]
 [   0    0    0 2837 7638 2687 1832 6147]
 [   0    0    0 2837 7638 2687 1832  384]
 [   0    0    0  819 4995 2813 5021 3012]
 [   0    0    0    0 9526 2121 6212 1832]]


In [13]:
## feature representation
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step


array([[[-0.04045558, -0.04928527, -0.02233683, -0.00065931,
          0.0435561 ,  0.04542695,  0.04204749, -0.04940343,
          0.04411043,  0.03832923],
        [-0.04045558, -0.04928527, -0.02233683, -0.00065931,
          0.0435561 ,  0.04542695,  0.04204749, -0.04940343,
          0.04411043,  0.03832923],
        [-0.04045558, -0.04928527, -0.02233683, -0.00065931,
          0.0435561 ,  0.04542695,  0.04204749, -0.04940343,
          0.04411043,  0.03832923],
        [-0.04045558, -0.04928527, -0.02233683, -0.00065931,
          0.0435561 ,  0.04542695,  0.04204749, -0.04940343,
          0.04411043,  0.03832923],
        [-0.04748403, -0.01730053,  0.01935288,  0.01295931,
         -0.04700997,  0.01354847,  0.04335301,  0.00563502,
         -0.00852964, -0.02119577],
        [-0.02185823,  0.02695123,  0.01566663, -0.02724212,
          0.03355087,  0.03013342,  0.01923962, -0.02362957,
          0.03024281,  0.04159636],
        [ 0.03698004, -0.01268642, -0.03439064, -0.0

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 4995, 8565, 5021,  613], dtype=int32)

In [19]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step


array([[[-0.04045558, -0.04928527, -0.02233683, -0.00065931,
          0.0435561 ,  0.04542695,  0.04204749, -0.04940343,
          0.04411043,  0.03832923],
        [-0.04045558, -0.04928527, -0.02233683, -0.00065931,
          0.0435561 ,  0.04542695,  0.04204749, -0.04940343,
          0.04411043,  0.03832923],
        [-0.04045558, -0.04928527, -0.02233683, -0.00065931,
          0.0435561 ,  0.04542695,  0.04204749, -0.04940343,
          0.04411043,  0.03832923],
        [-0.04045558, -0.04928527, -0.02233683, -0.00065931,
          0.0435561 ,  0.04542695,  0.04204749, -0.04940343,
          0.04411043,  0.03832923],
        [-0.04748403, -0.01730053,  0.01935288,  0.01295931,
         -0.04700997,  0.01354847,  0.04335301,  0.00563502,
         -0.00852964, -0.02119577],
        [-0.02185823,  0.02695123,  0.01566663, -0.02724212,
          0.03355087,  0.03013342,  0.01923962, -0.02362957,
          0.03024281,  0.04159636],
        [ 0.03698004, -0.01268642, -0.03439064, -0.0